//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADSLanchonete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public int IdCategoria { get; set; }
        public string NomeCategoria { get; set; }
    }
}
